services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: alga
      POSTGRES_PASSWORD: alga123
      POSTGRES_DB: alga
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: alga
      DB_PASS: alga123
      DB_NAME: alga
      PORT: "3000"
    ports:
      - "3000:3000"

volumes:
  pgdata:
